version: "3.7"
  
services:
  frontend:
    build: .
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 8080:3000
  api:
    build: .
    depends_on:
      - database
    volumes:
      - ./api:/app/
    ports:
      - 8000:3000
  # Infrastructure Services
  database: 
    image: mysql
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=pickit